run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - gosimple
    - goconst
    - gocyclo
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/ferchd/tm2hsl

issues:
  exclude-use-default: false
  exclude:
    - "G404"  # Use of weak random number generator